
CREATE TABLE permits (
    id FLOAT PRIMARY KEY,
    permit TEXT,
    permit_type TEXT,
    review_type TEXT,
    application_start_date TIMESTAMP,
    issue_date TIMESTAMP,
    processing_time INT,
    street_number TEXT,
    street_direction TEXT,
    street_name TEXT,
    work_description TEXT,
    building_fee_paid FLOAT,
    zoning_fee_paid FLOAT,
    other_fee_paid FLOAT,
    subtotal_paid FLOAT,
    building_fee_unpaid FLOAT,
    zoning_fee_unpaid FLOAT,
    other_fee_unpaid FLOAT,
    subtotal_unpaid FLOAT,
    building_fee_waived FLOAT,
    building_fee_subtotal FLOAT,
    zoning_fee_subtotal FLOAT,
    other_fee_subtotal FLOAT,
    zoning_fee_waived FLOAT,
    other_fee_waived FLOAT,
    subtotal_waived FLOAT,
    total_fee FLOAT,
    reported_cost FLOAT,
    contact_1_city VARCHAR,
    contact_1_name VARCHAR,
    contact_1_state VARCHAR,
    contact_1_type VARCHAR,
    contact_1_zipcode VARCHAR,
    latitude NUMERIC,
    longitude NUMERIC,
    location JSONB,
    xcoordinate NUMERIC,
    ycoordinate NUMERIC
);


